dbConfig:
    dbConfigFile: plutus-pab.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:8090

nodeServerConfig:
  pscSocketPath: "/home/agustin/plank/simple-smart-contract/testnet/node.sock"
  pscBaseUrl: "localhost"
  pscKeptBlocks: 2160
  pscNetworkId: "27182" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1652806800000
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode
  pscProtocolParametersJsonPath: "/home/agustin/plank/concurrent-sc/testnet/testnet.protocol"

chainIndexConfig:
  ciBaseUrl: http://35.202.113.38:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9085
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9086

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    { "tag" : "PointAtGenesis" }
    # { "tag" : "Point"
    # , "pointBlockId" : "613d23b8df670e3692f4e4ab59b179778519de15999ee1a51077fcc02a48abaa"
    # , "pointSlot" : { "getSlot" : 45656608 }
    # }


# Optional EKG Server Config
# ----
# monitoringConfig:
#   monitoringPort: 9090
